name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GO_VERSION: "1.21.0"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check out
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Build wasm
        run: go build -ldflags="-s -w" -v -o frontend/static/calculator.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      - name: Build frontend for Cloudflare (root path)
        working-directory: frontend
        run: |
          bun install
          bun run build
        env:
          BASE_PATH: ''

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fa820361b3084379f0646b645f81aa94
          command: pages deploy ./frontend/build --project-name=timeless-jewels-cn --branch=main

      - name: Build frontend for GitHub Pages (/timeless-jewels)
        working-directory: frontend
        run: bun run build
        env:
          BASE_PATH: '/timeless-jewels'

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          exclude_assets: ""
